---
default:
  cdn:
    dev-spa-spycloud:
      cache_policy_name: Managed-CachingOptimized
      aliases: []
      origin_access_identities:
        spa-apycloud: "SPA SpyCloud Bucket OAI"
      function_association:
        viewer-request:
          lambda: index

  # This might seem like duplication of code, unfortunately the function/lambda needs to exists before I can associate it with cloudfront
  functions:
  - index

  # While the wafv2 config can be part of the cdn object above, I think having a clear
  # seperation of resources makes updating and reading easier
  wafv2:
    dev-spa-spycloud:
      allow_default_action: false # if set to false iw till block requests by default
      white_list:
      - 3.121.56.176/32 # IP address that needs to be whitelisted as per the instructions
