#dev-use1:
default:
  s3:
    - dev-spa-spycloud
  cdn:
    dev-spa-spycloud:
      cache_policy_name: Managed-CachingOptimized
      aliases: []
      root_object: index.html
      origin_access_identities:
        spa-apycloud: "SPA SpyCloud Bucket OAI"
      origins: []
      #  - domain_name: kaia-deeplink-service-msk-eu-dev-226977328153.s3.eu-central-1.amazonaws.com
      function_association:
        viewer-requests:
          lambda: spa-spycloud
  functions:
  - "functions/index.html"
  access:
   - 3.121.56.176 # needs to be a whitelisted ip address, so waf needs to be enabled?
