default:
  cdn:
    dev-spa-spycloud:
      cache_policy_name: Managed-CachingOptimized
      aliases: []
      origin_access_identities:
        spa-apycloud: "SPA SpyCloud Bucket OAI"
      function_association:
        viewer-request:
          lambda: index
  # This might seem like duplication of code, unfortunately the function/lambda needs to exists before I can associate it with cloudfront
  functions:
  - index
  access:
   - 3.121.56.176 # needs to be a whitelisted ip address, so waf needs to be enabled?

#TODO:
# how to 'fix cannot delete function because it's in use????'
# Workaround: you have to remove the function association, save the changes, and then run terraform apply
# Add waf
# Add shell to copy app/index.html to s3 bucket
